- name: Run docker image hoangndst/vdt-backend:latest
  docker_container:
    name: backend
    image: hoangndst/vdt-backend:latest
    restart_policy: unless-stopped
    networks:
      - name: "{{ NETWORK_NAME }}"
    hostname: backend
    env:
      MONGO_HOST: "{{ MONGO_HOST }}}"
      MONGO_PORT: "{{ MONGO_PORT }}"
      MONGO_USERNAME: "{{ MONGO_USERNAME }}"
      MONGO_PASSWORD: "{{ MONGO_PASSWORD }}"
      ANSIBLE_HOST: "{{ ansible_host }}"
    ports:
      - "5000:5000"
  become: yes
  tags: docker

export MONGO_HOST=127.0.0.1
export MONGO_PORT=27017
export MONGO_USERNAME=hoangndst
export MONGO_PASSWORD=Hoang2002
export ANSIBLE_HOST=127.0.0.1