version: '3.9'

networks:
    traefik_default:
        external: true
volumes:
    todo_data:
        external: true
    mariadb_data:
        external: true  
services:
    todo:
        image: vikunja/vikunja
        container_name: todo
        hostname: todo
        environment:
            VIKUNJA_SERVICE_PUBLICURL: todo.hoangnd.freeddns.org
            VIKUNJA_DATABASE_HOST: mariadb
            VIKUNJA_DATABASE_PASSWORD: Hoang2002
            VIKUNJA_DATABASE_TYPE: mysql
            VIKUNJA_DATABASE_USER: hoangnd
            VIKUNJA_DATABASE_DATABASE: vikunja
            VIKUNJA_SERVICE_JWTSECRET: mishychocobobatea
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.todo.entrypoints=websecure"
            - "traefik.http.routers.todo.rule=Host(`todo.hoangnd.freeddns.org`)"
            - "traefik.http.routers.todo.service=todo"
            - "traefik.http.services.todo.loadbalancer.server.port=3456"
            - "traefik.docker.network=traefik_default"
            - "traefik.http.routers.todo.tls=true"
        # ports:
        #     - 3456:3456
        volumes:
            - todo_data:/app/vikunja/files
        restart: unless-stopped
        networks:
            - traefik_default
    db:
        image: mariadb:10
        hostname: mariadb
        container_name: mariadb
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            MYSQL_ROOT_PASSWORD: Hoang2002
            MYSQL_USER: hoangnd
            MYSQL_PASSWORD: Hoang2002
            MYSQL_DATABASE: vikunja
        volumes:
            - mariadb_data:/var/lib/mysql
        restart: unless-stopped
        networks:
            - traefik_default
