- name: Deploy load balancer
  docker_container:
    name: loadbalancer
    image: traefik:v2.9
    restart_policy: unless-stopped
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/traefik:/etc/traefik
      - "{{ LB_VOLUME }}:/etc/traefik"
    networks:
      - name: "{{ NETWORK_NAME }}"
    hostname: loadbalancer
    env:
      - "DYNU_API_KEY={{ DYNU_API_KEY }}"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network={{ NETWORK_NAME }}"
      - "traefik.http.routers.traefik.rule=Host(`{{ TRAEFIK_DOMAIN }}`)"
      - "traefik.http.routers.traefik.service=traefik"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=production"
  become: yes
- name: Copy traefik dynamic config file to container
  docker_copy:
    src: dynamic.yaml.j2
    dest: /etc/traefik/dynamic.yaml
    container: loadbalancer