apiVersion: v1
kind: Service
metadata:
  name: argocd-server-svc
  namespace: argocd
spec:
  selector:
    app.kubernetes.io/name: argocd-server
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30008
  type: NodePort
