apiVersion: v1
kind: PersistentVolume
metadata:
  name: traefik-pv
  namespace: traefik
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /certs