kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: traefik-pvc
  namespace: traefik
spec:
  storageClassName: nfs-client-retain
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 128Mi
