apiVersion: apps/v1
kind: Deployment
metadata:
  name: vdt-frontend
  namespace: vdt
  labels:
    app: vdt-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vdt-frontend
  template:
    metadata:
      labels:
        app: vdt-frontend
    spec:
      containers:
      - name: vd-frontend
        image: hoangndst/vdt-frontend:latest
        ports:
        - containerPort: 80
