- name: Create /etc/containerd/ directory
  file:
    path: /etc/containerd/
    state: directory
    mode: 0755
  tags:
  - containerd
- name: Upload files/config.toml
  copy:
    src: files/config.toml
    dest: /etc/containerd/config.toml
    mode: 0644
  tags:
  - containerd
- name: systemctl restart containerd
  shell: systemctl restart containerd
  tags: 
  - containerd