version: '3'
networks:
  traefik_default:
    external: true
services:
  app:
    container_name: pm
    image: 'hoangndst/pm:latest'
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pm.entrypoints=websecure"
      - "traefik.http.routers.pm.rule=Host(`pm.hoangndst.freeddns.org`)"
      - "traefik.http.routers.pm.service=pm"
      - "traefik.http.services.pm.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik_default"
    networks:
      - traefik_default