groups:
- name: cadvisor
  rules:
  - alert: ContainerKilled
    expr: time() - container_last_seen > 60
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: Container {{ $labels.name }} was killed (instance {{ $labels.instance }})
      value: '{{ $value }}'
      labels: '{{ $labels }}'
      description: "A container has disappeared\ncontainer_name = {{ $labels.name }}\ncontainer_image = {{ $labels.image }}\ninstance = {{ $labels.instance }}"
  - alert: ContainerCpuUsage
    expr: (sum(rate(container_cpu_usage_seconds_total{name!=""}[3m])) BY (instance, name) * 100) > 80
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: Container {{ $labels.name }} CPU usage (instance {{ $labels.instance }})
      value: '{{ $value }}'
      labels: '{{ $labels }}'
      description: "Container CPU usage is above 80%\ncontainer_name = {{ $labels.name }}\ncontainer_cpu_usage_seconds_total = {{ $value }}\ncontainer_image = {{ $labels.image }}\ninstance = {{ $labels.instance }}"
  - alert: ContainerMemoryUsage
    expr: (sum(container_memory_working_set_bytes{name!=""}) BY (instance, name) / sum(container_spec_memory_limit_bytes > 0) BY (instance, name) * 100) > 80
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: Container {{ $labels.name }} Memory usage (instance {{ $labels.instance }})
      value: '{{ $value }}'
      labels: '{{ $labels }}'
      description: "Container Memory usage is above 80%\ncontainer_name = {{ $labels.name }}\ncontainer_memory_working_set_bytes = {{ $value }}\ncontainer_image = {{ $labels.image }}\ninstance = {{ $labels.instance }}"
  - alert: ContainerVolumeUsage
    expr: (1 - (sum(container_fs_inodes_free{name!=""}) BY (instance) / sum(container_fs_inodes_total) BY (instance))) * 100 > 80
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: Container Volume usage (instance {{ $labels.instance }})
      value: '{{ $value }}'
      labels: '{{ $labels }}'
      description: "Container Volume usage is above 80%\ncontainer_fs_inodes_free = {{ $value }}\ninstance = {{ $labels.instance }}"

