version: "3.6"
networks:
  rabbitmq-prometheus:
    external: true
  traefik_default:
    external: true
volumes:
  rabbitmq-prometheus_prometheus:
  rabbitmq-prometheus_grafana:
services:
  grafana:
    container_name: grafana
    image: grafana/grafana-oss:latest
    # reverse proxy traefik
    # ports:
    #   - "3000:3000"
    networks:
      - "rabbitmq-prometheus"
      - "traefik_default"
    volumes:
      - rabbitmq-prometheus_grafana:/var/lib/grafana
      - /home/hoangndst/stuffops/monitoring/grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/rabbitmq.yaml
      - /home/hoangndst/stuffops/monitoring/grafana/datasources.yml:/etc/grafana/provisioning/datasources/prometheus.yaml
      - /home/hoangndst/stuffops/monitoring/grafana/dashboards:/dashboards
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.monitor.entrypoints=websecure"
      - "traefik.http.routers.monitor.rule=Host(`grafana.hoangndst.freeddns.org`)"
      - "traefik.http.routers.monitor.service=grafana"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.routers.monitor.tls=true"
      - "traefik.http.routers.monitor.tls.certresolver=production"
    environment:
      # https://grafana.com/plugins/flant-statusmap-panel
      # https://grafana.com/plugins/grafana-piechart-panel
      # https://grafana.com/plugins/grafana-polystat-panel
      # https://grafana.com/plugins/jdbranham-diagram-panel
      # https://grafana.com/plugins/michaeldmoore-multistat-panel
      # https://grafana.com/plugins/vonage-status-panel
      # https://grafana.com/plugins/yesoreyeram-boomtable-panel
      GF_INSTALL_PLUGINS: "flant-statusmap-panel,grafana-piechart-panel"
  prometheus:
    # https://hub.docker.com/r/prom/prometheus/tags
    image: prom/prometheus:lastest
    networks:
      - "rabbitmq-prometheus"
    ports:
      - "9090:9090"
    volumes:
      - rabbitmq-prometheus_prometheus:/prometheus
      - /home/hoangndst/stuffops/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
  node-exporter:
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    # https://hub.docker.com/r/prom/node-exporter/tags
    image: prom/node-exporter:v1.2.0
    networks:
      - "rabbitmq-prometheus"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
  cadvisor:
    expose:
      - 8080
    # https://hub.docker.com/r/google/cadvisor/tags
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    networks:
      - "rabbitmq-prometheus"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      #- /cgroup:/cgroup:ro #doesn't work on MacOS only for Linux