version: "3.2"
volumes:
  data:
    driver: local
networks:
  traefik_default:
    external: true
services:
  app:
    image: nextcloud
    restart: always
    volumes:
      - data:/var/www/html
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=hoangndst
      - POSTGRES_PASSWORD=Postgres2002*
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.hoangndst.freeddns.org
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.rule=Host(`cloud.hoangndst.freeddns.org`)"
      - "traefik.http.routers.nextcloud.service=nextcloud"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.tls.certresolver=production"
    networks:
      - traefik_default