version: '3'

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
networks:
  traefik_default:
    external: true
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /etc/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    networks:
      - traefik_default
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.monitor.entrypoints=websecure"
      - "traefik.http.routers.monitor.rule=Host(`monitor.hoangndst.freeddns.org`)"
      - "traefik.http.routers.monitor.service=grafana"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.routers.monitor.tls=true"
      - "traefik.http.routers.monitor.tls.certresolver=production"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - traefik_default
    restart: unless-stopped

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    # network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    networks:
      - traefik_default
  cadvisor:
    # TODO: latest tag is not updated, check latest release https://github.com/google/cadvisor/releases
    image: gcr.io/cadvisor/cadvisor:v0.46.0
    container_name: cadvisor
    # ports:
    #   - "8080:8080"
    # network_mode: host
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /media/sd500/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - traefik_default
    devices:
      - /dev/kmsg
    restart: unless-stopped
    privileged: true