apiVersion: apps/v1
kind: Deployment
metadata:
  name: vdt-backend
  namesapce: vdt-app
  labels:
    app: vdt-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vdt-backend
  template:
    metadata:
      labels:
        app: vdt-backend
    spec:
      containers:
      - name: vd-backend
        image: hoangndst/vdt-backend:latest
        ports:
        - containerPort: 5000
      env:
      - name: MONGO_HOST
        value: "mongodb://vdt-mongodb:27017"
      - name: MONGO_PORT
        value: "27017"
      - name: MONGO_USERNAME
        value: "root"
      - name: MONGO_PASSWORD
        
