networks:
  traefik_cloudflare:
    external: true
services:
  mishy:
    container_name: mishy
    image: 'hoangndst/mishy:v0.0.2'
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mishy.entrypoints=websecure"
      - "traefik.http.routers.mishy.rule=Host(`mishy.hoangndst.com`)"
      - "traefik.http.routers.mishy.service=mishy"
      - "traefik.http.services.mishy.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_cloudflare"
      - "traefik.http.routers.mishy.tls=true"
      - "traefik.http.routers.mishy.tls.certresolver=hoangndst-prod"
    networks:
      - traefik_cloudflare
