- name: Check if python3-pip is installed
  apt:
    name: python3-pip
    state: present
  become: yes
  tags: python3-pip
- name: Install docker module for python if not exists
  pip:
    name: docker
    state: present
  become: yes
  tags: python3-pip
- name: Check if docker network exists
  docker_network_info:
    name: "{{ NETWORK_NAME }}"
  register: docker_network
  become: yes
  tags: docker
- name: Create docker network
  docker_network:
    name: "{{ NETWORK_NAME }}"
    state: present
  when: docker_network.exists == false
  become: yes
  tags: docker
- name: Check if docker MONGO_DB_VOLUME exists
  docker_volume_info:
    name: "{{ MONGO_DB_VOLUME }}"
  register: docker_db_volume
  become: yes
  tags: docker
- name: Create docker nfs MONGO_DB_VOLUME
  docker_volume:
    name: "{{ MONGO_DB_VOLUME }}"
    driver: local
    driver_options:
      type: nfs
      o: addr={{ NFS_SERVER_IP }},rw
      device: ":{{ NFS_SHARE_PATH }}"
  when: docker_db_volume.exists == false
  become: yes
  tags: docker