---
# Source: nexus-repository-manager/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nexus-nexus-repository-manager
  labels:
    helm.sh/chart: nexus-repository-manager-56.0.0
    app.kubernetes.io/name: nexus-repository-manager
    app.kubernetes.io/instance: nexus
    app.kubernetes.io/version: "3.56.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8081
      protocol: TCP
      name: nexus-ui
  selector:
    app.kubernetes.io/name: nexus-repository-manager
    app.kubernetes.io/instance: nexus
