---
# Source: kube-prometheus-stack/templates/prometheus-operator/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kube-prometheus-stack-moni-operator
  namespace: monitoring
  labels:
    app: monitoring-operator
    
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/version: "46.6.0"
    app.kubernetes.io/part-of: monitoring
    chart: kube-prometheus-stack-46.6.0
    release: "kube-prometheus-stack"
    heritage: "Helm"
spec:
  ports:
  - name: https
    port: 443
    targetPort: https
  selector:
    app: monitoring-operator
    release: "kube-prometheus-stack"
  type: "ClusterIP"
