version: '3'
volumes:
  jenkins_data:
    external: true
networks:
  traefik_default:
    external: true
services:
  app:
    container_name: jenkins
    image: 'hoangndst/jenkins:lts-jdk11'
    restart: unless-stopped
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - JAVA_OPTS=-Duser.timezone=Asia/Ho_Chi_Minh
      - DOCKER_HOST=tcp://raspbaby:2376
      - DOCKER_CERT_PATH=/var/jenkins_home/.docker
      - DOCKER_TLS_VERIFY=1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkins.entrypoints=websecure"
      - "traefik.http.routers.jenkins.rule=Host(`jenkins.hoangndst.freeddns.org`)"
      - "traefik.http.routers.jenkins.service=jenkins"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.routers.jenkins.tls=true"
      - "traefik.http.routers.jenkins.tls.certresolver=production"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_data:/var/jenkins_home
      - /home/hoangndst/.docker:/var/jenkins_home/.docker
    networks:
      - traefik_default