---
# Source: x509-certificate-exporter/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: x509-cert-exporter
  namespace: monitoring
  labels:
    helm.sh/chart: x509-certificate-exporter-0.0.0
    app.kubernetes.io/name: x509-cert-exporter
    app.kubernetes.io/instance: x509
    app.kubernetes.io/version: "0.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: x509-cert-exporter
      app.kubernetes.io/instance: x509
  replicas: 1
  template:
    metadata:
      labels:
        helm.sh/chart: x509-certificate-exporter-0.0.0
        app.kubernetes.io/name: x509-cert-exporter
        app.kubernetes.io/instance: x509
        app.kubernetes.io/version: "0.0.0"
        app.kubernetes.io/managed-by: Helm
      annotations:
        prometheus.io/port: "9793"
        prometheus.io/scrape: "true"
    spec:
      restartPolicy: Always
      serviceAccountName: x509-cert-exporter
      containers:
      - name: x509-certificate-exporter
        securityContext:
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 65534
          runAsUser: 65534
        resources:
          limits:
            cpu: 200m
            memory: 150Mi
          requests:
            cpu: 20m
            memory: 20Mi
        image: docker.io/enix/x509-certificate-exporter:3.6.0
        imagePullPolicy: IfNotPresent
        args:
        - --watch-kube-secrets
        - --secret-type=kubernetes.io/tls:tls.crt
        - --max-cache-duration=300s
        - --listen-address=:9793
        ports:
        - name: metrics
          containerPort: 9793
