version: '3.6'
# The version of the compose file. This is optional, but recommended. More info: https://docs.docker.com/compose/compose-file/#compose-and-docker-compatibility-matrix
# The version of the compose file. This is optional, but recommended. More info: https://docs.docker.com/compose/compose-file/#compose-and-docker-compatibility-matrix
networks:
  traefik_default:
    external: true
  rabbitmq-prometheus:
    external: true
volumes:
  rabbitmq_data:
    external: true
services:
  app:
    container_name: rabbitmq
    hostname: rabbitmq
    image: 'rabbitmq:management'
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=hoangndst
      - RABBITMQ_DEFAULT_PASS=Hoang2002
      - RABBITMQ_ERLANG_COOKIE=rabbitmq-prometheus
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rabbitmq.entrypoints=websecure"
      - "traefik.http.routers.rabbitmq.rule=Host(`rabbitmq.hoangndst.freeddns.org`)"
      - "traefik.http.routers.rabbitmq.tls=true"
      - "traefik.http.routers.rabbitmq.service=rabbitmq"
      - "traefik.http.services.rabbitmq.loadbalancer.server.port=15672"
      - "traefik.docker.network=traefik_default"
    cap_add:
      - ALL
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - /home/hoangndst/stuffops/rabbitmq/monitoring-rabbitmq/rabbitmq-overview.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - /home/hoangndst/stuffops/rabbitmq/monitoring-rabbitmq/rabbitmq-overview-definitions.json:/etc/rabbitmq/rabbitmq-definitions.json:ro
    networks:
      - traefik_default
      - rabbitmq-prometheus