version: "3.9"

volumes:
  databag_data:
    external: true
networks:
  traefik_default:
    external: true
services:
  databag:
    container_name: databag
    image: balzack/databag:latest
    # ports:
    #   - "7000:7000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.databag.entrypoints=websecure"
      - "traefik.http.routers.databag.rule=Host(`databag.hoangnd.freeddns.org`)"
      - "traefik.http.routers.databag.service=databag"
      - "traefik.http.services.databag.loadbalancer.server.port=7000"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.routers.databag.tls=true"
    volumes:
      - databag_data:/var/lib/databag
    networks:
      - traefik_default
